version: 2
jobs:
    build:
        working_directory: /conda-build
        docker:
            - image: condaforge/linux-anvil
        steps:
            - run: |
                set -x
                ls /opt/conda
                ls /opt/docker/bin
                source /opt/docker/bin/entrypoint_source
            - checkout
            - run: |
                conda config --add channels conda-forge
                conda update conda conda-build
                conda install conda-build-all
            - run: conda-build-all conda --matrix-conditions "python >=2.7,<3|>=3.5"
