version: 2
jobs:
    build:
        docker:
            - image: condaforge/linux-anvil
        steps:
            - checkout
            - run: conda config --add channels conda-forge
            - run: conda update conda conda-build
            - run: conda install conda-build-all
            - run: conda-build-all conda --matrix-conditions "python >=2.7,<3|>=3.5"
